version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
